# Generated by Django 4.2.6 on 2023-10-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='summary',
        ),
        migrations.AddField(
            model_name='employer',
            name='country',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='income',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='topic',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
