# Generated by Django 4.2.6 on 2023-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0003_employer_type_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(upload_to='jobs/'),
        ),
    ]
