# Generated by Django 4.2.6 on 2023-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0004_alter_employer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='type_job',
            field=models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Intership', 'Intership'), ('Remote', 'Remote')], max_length=100),
        ),
    ]
