# Generated by Django 4.2.6 on 2023-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0005_alter_employer_type_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='summary',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
