# Generated by Django 4.2.7 on 2023-11-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0006_employer_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='summary',
        ),
    ]
