# Generated by Django 4.2.6 on 2023-10-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0006_employer_summary'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='about_me',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='req_text',
            new_name='responsibility',
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='income',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='logo',
            field=models.ImageField(default='1', upload_to='jobs-detail/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='summary_Employer',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='joblist.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='topic',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='type_job',
            field=models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Intership', 'Intership'), ('Remote', 'Remote')], default='1', max_length=100),
            preserve_default=False,
        ),
    ]
