# Generated by Django 4.2.7 on 2023-11-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0007_remove_employer_summary'),
        ('jobs', '0002_rename_about_me_employee_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
                ('type_job', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Intership', 'Intership'), ('Remote', 'Remote')], max_length=100)),
                ('logo', models.ImageField(upload_to='jobs/')),
                ('summary1', models.CharField(max_length=100)),
                ('summary2', models.CharField(max_length=100)),
                ('summary3', models.CharField(max_length=100)),
                ('summary4', models.CharField(max_length=100)),
                ('summary5', models.CharField(max_length=100)),
                ('response1', models.CharField(max_length=100)),
                ('response2', models.CharField(max_length=100)),
                ('response3', models.CharField(max_length=100)),
                ('response4', models.CharField(max_length=100)),
                ('response5', models.CharField(max_length=100)),
                ('company1', models.CharField(max_length=100)),
                ('company2', models.CharField(max_length=100)),
                ('company3', models.CharField(max_length=100)),
                ('company4', models.CharField(max_length=100)),
                ('company5', models.CharField(max_length=100)),
                ('employ', models.ManyToManyField(to='joblist.employer')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
