# Generated by Django 4.2.7 on 2023-11-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0007_remove_employer_summary'),
        ('jobs', '0003_employer_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Employee',
        ),
    ]
