# Generated by Django 4.2.7 on 2023-11-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_employer_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='response1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='response2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='response3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='response4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='response5',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='summary1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='summary2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='summary3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='summary4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='summary5',
        ),
    ]
