# Generated by Django 4.2.7 on 2023-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_employee_company1_remove_employee_company2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employ',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='income',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type_job',
        ),
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
