# Generated by Django 4.2.7 on 2023-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_country_employee_name_remove_employee_employ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(default='1', upload_to='user/'),
            preserve_default=False,
        ),
    ]
