# Generated by Django 4.2.7 on 2023-11-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0008_employer_company1_employer_company2_and_more'),
        ('jobs', '0007_employee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employ',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='joblist.employer'),
            preserve_default=False,
        ),
    ]
